spring:
  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/pi?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true